name: app-ci-cd
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: us-east-1
  REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:
  build_test_containerize_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build & test
        run: |
          mvn -B -q -f ingest-service/pom.xml -DskipTests=false -Dspotless.apply=false verify
          mvn -B -q -f api-gateway/pom.xml -DskipTests=false -Dspotless.apply=false verify
      - name: Build Docker images
        run: |
          docker build -t $REGISTRY/ingest-service:${{ github.sha }} ./ingest-service
          docker build -t $REGISTRY/api-gateway:${{ github.sha }} ./api-gateway
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images
        run: |
          docker push $REGISTRY/ingest-service:${{ github.sha }}
          docker push $REGISTRY/api-gateway:${{ github.sha }}
      - name: Configure AWS creds via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-oidc-deploy
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name telemetry-eks --region $AWS_REGION
      - name: Helm deploy
        run: |
          helm upgrade --install ingest helm/ingest-service             --set image.repository=$REGISTRY/ingest-service --set image.tag=${{ github.sha }}
          helm upgrade --install gateway helm/api-gateway             --set image.repository=$REGISTRY/api-gateway --set image.tag=${{ github.sha }}
